databases:
  - name: khaled_project_1_development
    ipAllowList: []
    databaseName: khaled_project_1_development
    user: khaled

services:
  - type: web
    name: khaled
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: khaled_project_1_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
